spring.application.name=llm_router
spring.datasource.url=jdbc:h2:file:./data/llm-router-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.ai.chat.memory.repository.jdbc.initialize-schema=always

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console